### ISSUE TITLE
Make compatible with mongoose 4.x

### ISSUE THREAD

**Issue by matthew-b-payne** [njoyard/yarm#5]
Current version does not support mongoose 4.  If yarm is not dead, please bring up to date.

**Comment by njoyard** [comment]
I have no time for this ATM, but it is also on my wishlist.
Feel free to submit a pull request :)

**Comment by matthew-b-payne** [comment]
I created a fork that is compliant with mongoose 4.x and mongodb 2.x.

https://github.com/matthew-b-payne/yarm

**Comment by njoyard** [comment]
Oh nice, I thought this would have taken more work than that. Would you mind submitting a pull request ?

**Comment by matthew-b-payne** [comment]
I created a pull request.

https://travis-ci.org/njoyard/yarm/builds/78336167

Based on the test results there looks like DocumentArray handling still
needs to be looked at.

Below is a blurb from the release notes and DocumentArrays.
https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes


   - Array and DocumentArray are now functions that return an array, rather
   than constructors. For instance, new MongooseArray([]) instanceof
   MongooseArray isfalse in 4.0. To check whether an array is a
   MongooseArray, use theisMongooseArray and isMongooseDocumentArray
properties.
   This is in order for Mongoose's isomorphic component (see #2254
   <https://github.com/LearnBoost/mongoose/issues/2254>) to support non-ES5
   compatible browsers (such as IE8) without a shim.

**Comment by njoyard** [comment]
Thanks a lot.
I'll take some time soon to have a look at those remaining issues.

**Comment by njoyard** [comment]
Hey, FYI I'm working on that right now. Seems a lot simpler than I previously expected.

**Comment by njoyard** [comment]
Fixed as of 0.4.0

**Comment by matthew-b-payne** [comment]
Awesome, good job!.

Matt
